"""Constants for SkyCooker integration."""

# Integration version
VERSION = "0.0.8"

# Model codes
MODELS_0 = 0x00
MODELS_1 = 0x01
MODELS_2 = 0x02
MODELS_3 = 0x03
MODELS_4 = 0x04
MODELS_5 = 0x05  # RMC-M40S, RMC-M42S
MODELS_6 = 0x06
MODELS_7 = 0x07  # RMC-M22xS series

# Command constants
COMMAND_GET_VERSION = 0x01
COMMAND_GET_STATUS = 0x06
COMMAND_TURN_ON = 0x03
COMMAND_TURN_OFF = 0x04
COMMAND_SET_MAIN_MODE = 0x05
COMMAND_COMMIT_SETTINGS = 0x09
COMMAND_SYNC_TIME = 0x0A

# Mode constants
MODE_STANDBY = 0x00
MODE_MULTI_CHEF = 0x01
MODE_RICE_CEREALS = 0x02
MODE_LANGUOR = 0x03
MODE_PILAF = 0x04
MODE_FRYING = 0x05
MODE_STEWING = 0x06
MODE_PASTA = 0x07
MODE_BAKING = 0x08
MODE_STEAMING = 0x09
MODE_YOGURT = 0x0A
MODE_DOUGH = 0x0B
MODE_KEEP_WARM = 0x0C

# Light modes
LIGHT_OFF = 0x00
LIGHT_ON = 0x01
LIGHT_AUTO_OFF = 0x02

# Error codes
ERROR_NO_ERROR = 0x00
ERROR_OVERHEAT = 0x01
ERROR_SENSOR_ERROR = 0x02
ERROR_MOTOR_ERROR = 0x03
ERROR_LID_OPEN = 0x04
ERROR_LOW_WATER = 0x05
ERROR_HIGH_WATER = 0x06
ERROR_UNKNOWN = 0xFF

# Configuration keys
CONF_MAC = "mac"
CONF_PASSWORD = "password"
CONF_MODEL = "model"
CONF_NAME = "name"

# Device classes
DEVICE_CLASS_MULTICOOKER = "multicooker"
DEVICE_CLASS_LIGHT = "light"
DEVICE_CLASS_SWITCH = "switch"
DEVICE_CLASS_SENSOR = "sensor"
DEVICE_CLASS_NUMBER = "number"
DEVICE_CLASS_SELECT = "select"
DEVICE_CLASS_BUTTON = "button"

# Entity categories
ENTITY_CATEGORY_CONFIG = "config"
ENTITY_CATEGORY_DIAGNOSTIC = "diagnostic"
ENTITY_CATEGORY_SYSTEM = "system"

# Default values
DEFAULT_TIMEOUT = 10.0
DEFAULT_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_DELAY = 1.0

# Configuration keys
CONF_AUTH_KEY = "auth_key"

# Temperature constants
ROOM_TEMP = 25
BOIL_TEMP = 100