"""Constants for SkyCooker component."""

DOMAIN = "skycooker"
FRIENDLY_NAME = "SkyCooker"
MANUFACTORER = "Redmond"
SUGGESTED_AREA = "kitchen"

# Configuration constants
CONF_AUTH_KEY = "auth_key"
CONF_DEVICE_NAME = "device_name"
CONF_PERSISTENT_CONNECTION = "persistent_connection"
CONF_SCAN_TIMEOUT = "scan_timeout"
CONF_WAIT_TIME = "wait_time"
CONF_RETRIES = "retries"
CONF_CONNECTION_TIMEOUT = "connection_timeout"
CONF_DEVICE = "device"

# Default values
DEFAULT_AUTH_KEY = "00000000000000000000000000000000"
DEFAULT_DEVICE_NAME = "RMC-M40S"
DEFAULT_PERSISTENT_CONNECTION = True
DEFAULT_SCAN_TIMEOUT = 5
DEFAULT_WAIT_TIME = 2
DEFAULT_RETRIES = 3
DEFAULT_CONNECTION_TIMEOUT = 30
DEFAULT_SCAN_INTERVAL = 5

DATA_CONNECTION = "connection"
DATA_CANCEL = "cancel"
DATA_WORKING = "working"
DATA_DEVICE_INFO = "device_info"

DISPATCHER_UPDATE = "update"

ROOM_TEMP = 25
BOIL_TEMP = 100

BLE_SCAN_TIME = 3